# Generated by Django 4.2.3 on 2023-07-26 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrawResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('name', models.CharField(max_length=100, verbose_name='Party name')),
                ('description', models.CharField(max_length=500, verbose_name='Party description')),
                ('image', models.ImageField(blank=True, upload_to='static/img/parties')),
                ('draw_results', models.ManyToManyField(related_name='draw_results', through='party.DrawResult', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'parties',
                'db_table': 'party',
            },
        ),
        migrations.CreateModel(
            name='UserParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='users',
            field=models.ManyToManyField(related_name='parties', through='party.UserParty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='party.party'),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drawresult',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
