# Generated by Django 4.2.3 on 2023-08-09 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='duration',
            field=models.TimeField(default=datetime.datetime(2023, 8, 9, 13, 43, 30, 381038, tzinfo=datetime.timezone.utc), verbose_name='Time of party duration'),
            preserve_default=False,
        ),
    ]
