# Generated by Django 4.2.3 on 2023-08-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_alter_party_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparty',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
