# Generated by Django 4.2.3 on 2023-08-09 13:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_party_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='duration',
        ),
        migrations.AddField(
            model_name='party',
            name='finish_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 13, 47, 19, 866090, tzinfo=datetime.timezone.utc), verbose_name='Time when party will be ended'),
            preserve_default=False,
        ),
    ]
