# Generated by Django 4.2.3 on 2023-08-14 11:43

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0004_remove_userparty_joined_at_userparty_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=apps.core.models.generate_unique_image_name),
        ),
    ]
