# Generated by Django 4.2.3 on 2023-08-17 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answers',
            field=models.ManyToManyField(related_name='answers', through='question.UserPartyQuestionAnswer', to=settings.AUTH_USER_MODEL),
        ),
    ]
