# Generated by Django 4.2.3 on 2023-07-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Present',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None)),
                ('name', models.CharField(max_length=50, verbose_name='Present Name')),
                ('description', models.CharField(max_length=200, verbose_name='Present Description')),
                ('image', models.ImageField(blank=True, upload_to='static/img/present/')),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Present',
                'verbose_name_plural': 'Presents',
                'db_table': 'present',
            },
        ),
        migrations.CreateModel(
            name='UserPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_preferred', models.BooleanField(default=True)),
                ('present', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='present.present')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='present',
            name='users',
            field=models.ManyToManyField(related_name='present', through='present.UserPresent', to=settings.AUTH_USER_MODEL),
        ),
    ]
