# Generated by Django 4.2.3 on 2023-07-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='deleted_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
