# Generated by Django 4.2.3 on 2023-07-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0002_alter_present_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
