# Generated by Django 4.2.3 on 2023-07-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present', '0003_alter_present_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='present',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/present/'),
        ),
    ]
